server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      stat-view-servlet:
        allow: all
        login-password: 123456
        login-username: admin
        enabled: true
      web-stat-filter:
        enabled: true
      username: root
      password: 123456
      url: jdbc:mysql://124.71.25.233/springcloud
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #驼峰
    map-underscore-to-camel-case: true
  #所有别名类所在的包
  type-aliases-package: org.yuwh.springcloud.entities
logging:
  level:
    root: info
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true #在eureka中显示IP地址
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://practivate.xmind.net:7002/eureka/,http://activate.xmind.net:7001/eureka/ # 入驻地址
      defaultZone: http://activate.xmind.net:7001/eureka/ # 入驻地址