server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      stat-view-servlet:
        allow: all
        login-password: 123456
        login-username: admin
        enabled: true
      web-stat-filter:
        enabled: true
      username: root
      password: 123456
      url: jdbc:mysql://124.71.25.233/springcloud
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #驼峰
    map-underscore-to-camel-case: true
  #所有别名类所在的包
  type-aliases-package: org.yuwh.springcloud.entities
logging:
  level:
    root: info